services:
  # PostgreSQL database for Temporal
  temporal-db:
    image: postgres:13
    container_name: temporal-postgresql
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
      POSTGRES_DB: temporal
    ports:
      - "5432:5432"
    volumes:
      - temporal_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U temporal"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Temporal Server
  temporal:
    image: temporalio/auto-setup:1.22.0
    container_name: temporal-server
    depends_on:
      temporal-db:
        condition: service_healthy
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=temporal-db
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    ports:
      - "7233:7233"
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig
    healthcheck:
      test: ["CMD", "sh", "-c", "temporal operator cluster health --address $$(hostname -i):7233"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Temporal Web UI
  temporal-ui:
    image: temporalio/ui:2.21.3
    container_name: temporal-ui
    depends_on:
      temporal:
        condition: service_healthy
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    ports:
      - "8080:8080"

  # Temporal Worker
  temporal-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: temporal-worker
    depends_on:
      temporal:
        condition: service_healthy
    environment:
      # Temporal connection
      - TEMPORAL_SERVER=temporal:7233
      - TASK_QUEUE=default
      
      # Hot reload configuration
      - HOT_RELOAD_ENABLED=true
      - HOT_RELOAD_MODE=FileSystem
      
      # Artifactory configuration (for feed monitoring)
      # Uncomment and set these to use Artifactory feed monitoring:
      # - HOT_RELOAD_MODE=ArtifactoryFeed
      # - ARTIFACTORY_FEED_URL=https://your-artifactory.com/artifactory/api/nuget/v3/nuget-repo
      # - ARTIFACTORY_USERNAME=your-username
      # - ARTIFACTORY_PASSWORD=your-api-key
      # - ARTIFACTORY_POLL_INTERVAL_SECONDS=30
      # - ARTIFACTORY_PACKAGE_FILTERS=TemporalActivities,MyWorkflows
    volumes:
      # Mount a volume for package downloads when using feed monitoring
      - worker_packages:/tmp/TemporalWorker/FeedPackages
      # Optional: Mount host directory for file system monitoring
      # - ~/.nuget/packages:/home/temporal/.nuget/packages:ro
    restart: unless-stopped

volumes:
  temporal_db_data:
  worker_packages: